# Generated by Django 5.1.3 on 2025-02-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpackage',
            name='name',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('luxury', 'Luxury')], max_length=20),
        ),
    ]
