# Generated by Django 5.1.3 on 2025-02-22 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
