# Generated by Django 5.1.3 on 2025-02-24 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_eventpackage_name'),
        ('userapp', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_package',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='adminapp.eventpackage'),
            preserve_default=False,
        ),
    ]
